const express = require('express');
const { register, login, getMe, updateProfile, changePassword, deleteAccount, getPreferences, updatePreferences } = require('../controllers/authController');
const { protect } = require('../middleware/auth');
const router = express.Router();
router.post('/register', register);
router.post('/login', login);
router.get('/me', protect, getMe);
router.get('/preferences', protect, getPreferences);
router.put('/preferences', protect, updatePreferences);
router.put('/profile', protect, updateProfile);
router.put('/change-password', protect, changePassword);
router.delete('/account', protect, deleteAccount);
module.exports = router;
